accessKey = "YOUR-ACCESS-KEY-HERE"
baseUrl = "https://api.staffany.com"

# MongoDB Database parameters

CONNECTION_STRING = "YOUR-CONNECTION-STRING-HERE"
DATABASE = "YOUR-DATABASE-NAME-HERE"
COLLECTION = "YOUR-COLLECTION-NAME-HERE"

